runtime: python310

env: standard
env_variables:
  # APPENGINE_URL: https://astute-vortex-402901.uw.r.appspot.com
  debug: true
  DJANGO_SETTINGS_MODULE: "questmart.settings"

entrypoint: gunicorn -b :$PORT questmart.wsgi:application

handlers:
  - url: /static
    static_dir: static/

  - url: /media
    static_dir: media/

  - url: /.*
    script: auto
