# Generated by Django 4.1.13 on 2023-11-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photos',
            field=models.ImageField(upload_to=''),
        ),
    ]
