# Generated by Django 4.1.13 on 2023-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_item_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photos',
            field=models.ImageField(upload_to='items/photos'),
        ),
    ]
